### PR TITLE
Add Ultimate Bulletin Board / message-boards

### PR DESCRIPTION
**Pull request by nurbek91**
### website:
https://www.ubbcentral.com/purchase.php
### examples:
https://ubbdev.com/forums/ubbthreads.php/forum_summary.html
https://board.moparts.org/ubbthreads/ubbthreads.php
https://clubsi.com/

### CODE REVIEW

**Review by dhavalveera — CHANGES_REQUESTED** [review]
@nurbek91, Icon is missing for this PR

**Comment by nurbek91** [comment]
> @nurbek91, Icon is missing for this PR
Hey mate, thanks!!
Can you suggest an icon add to PR

**Comment by dhavalveera** [comment]
> > @nurbek91, Icon is missing for this PR
> 
> Hey mate, thanks!! Can you suggest an icon add to PR

can't we use this Logo => https://www.ubbcentral.com/forums/styles/images/ubb/logo.png

**Comment by nurbek91** [comment]
> > > @nurbek91, Icon is missing for this PR
> > 
> > 
> > Hey mate, thanks!! Can you suggest an icon add to PR
> 
> can't we use this Logo => https://www.ubbcentral.com/forums/styles/images/ubb/logo.png

need a transparent background

**Pull request merged**
