### PR TITLE
added engintron

### PR DESCRIPTION
**Pull request by ahmedelq**
## Website
https://engintron.com/

## Examples
https://nbdementiaguide.ca/
https://www.emremor.net/
https://manoslimpias.es/
https://unar.info/

### CODE REVIEW

**Review by nurbek91 — CHANGES_REQUESTED** [review]
Hey mate , thanks for PR!!
Need small changes 
transparent and 32x32 icon 
engintron

**Comment by ahmedelq** [comment]
@nurbek91 Thanks for the icon, updated. 
Is there any tool that automates icon creation?

**Comment by nurbek91** [comment]
> @nurbek91 Thanks for the icon, updated. Is there any tool that automates icon creation?

I do not know. Personally, I use Figma.

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
