### PR TITLE
Add Bricksite / page-builders

### PR DESCRIPTION
**Pull request by nurbek91**
### website
https://bricksite.io/pricing
### examples
https://rasmus-som-growth-marketeer-625471da34214be0669969cc.brick.site/
https://proadvisor-62626ef700c09aefcc43b3f0.brick.site/
https://bar-6265129d9b138f2ff4bd4d87.brick.site/

### CODE REVIEW

**Comment by nurbek91** [comment]
I don't understand what I did wrong ;(

**Comment by nurbek91** [comment]
I don't understand what I did wrong ;(

**Comment by AliasIO** [comment]
`sass` should be `saas`. 😂

**Comment by nurbek91** [comment]
@AliasIO , Hey mate, If the technology is for merged, does this mean that all extensions should see it?

**Comment by nurbek91** [comment]
Ah sorry I didn't update the extensions myself

**Comment by AliasIO** [comment]
Only if it's been released, you see the releases here:

https://github.com/wappalyzer/wappalyzer/releases

This was included in v6.10.26.

**Comment by nurbek91** [comment]
Thanks !! How could I fooled twice on the same tech :joy

**Pull request merged**
