### PR TITLE
Add PWA detection

### PR DESCRIPTION
**Pull request by ysm0622**
website:
- https://web.dev/progressive-web-apps/

examples: 
- https://web.dev/
- https://twitter.com/
- https://firebase.google.com/
- https://github.com/
- https://www.youtube.com/
- https://www.facebook.com/

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks! I don't think Accessibility is the right category for this, perhaps JavaScript frameworks or Miscellaneous?

**Comment by ysm0622** [comment]
> Thanks! I don't think Accessibility is the right category for this, perhaps JavaScript frameworks or Miscellaneous?

I don't think it's JavaScript framework. Changed to Miscellaneous. [6265d82](https://github.com/wappalyzer/wappalyzer/pull/6439/commits/6265d8219ca811a0681498325b4e34bd21e72783)

**Comment by nurbek91** [comment]
Hey mate @ysm0622  Can you tell me if this is a PWA site?
https://homehunter.ru/

**Comment by ysm0622** [comment]
> Hey mate @ysm0622 Can you tell me if this is a PWA site? https://homehunter.ru/

@nurbek91 yeah that website is PWA site. That has `link[rel='manifest']` dom.

**Pull request merged**
