### PR TITLE
New Category "Form Builder", New Detection: "FormAssembly"

### PR DESCRIPTION
**Pull request by mawiseman**
### About

https://www.g2.com/products/formassembly/

### Examples
IFrame
- https://www.uts.edu.au/study/find-a-course/graduate-diploma-business-administration

Embedded From
- https://www.uts.edu.au/current-students/managing-your-course/ask-uts/ask-uts/ask-uts-form
- https://industrynsw.tfaforms.net/f/RAA-special-disaster-assistance
- https://ap4.tfaforms.net/forms/resume/321
- https://pearson.tfaforms.net/256
- https://engineersaustralia.tfaforms.net/4859419
- https://score.tfaforms.net/16
- https://collegeboard.tfaforms.net/21
- https://wmchealthnetwork.tfaforms.net/253
- https://bpu.tfaforms.net/39
- https://suntrust.tfaforms.net/261723171

### CODE REVIEW

**Comment by dhavalveera** [comment]
@mawiseman -> when you make a PR to add a Technology, for every new technology it should be a new PR, not all the Technologies should be in a single PR

also, for every new Technology addition, you've to share at least 5 examples where this Technologies has been used

**Comment by dhavalveera** [comment]
please close this PR, and make a new PR for every new Technology @mawiseman

**Comment by mawiseman** [comment]
This PR is only for 1 technology: FormAssembly
What other technologies do you think have been included?

**Comment by AliasIO** [comment]
The PR is fine, it needs a few tweaks. The [locales](https://github.com/wappalyzer/wappalyzer/tree/master/src/drivers/webextension/_locales) need to be updated as well but I'll do that too. Thank you!

**Pull request merged**
