### PR TITLE
Add Skilljar (LMS)

### PR DESCRIPTION
**Pull request by kyletaylored**
Skilljar is one of the more prominent B2B LMS platforms.

### CODE REVIEW

**Review by dhavalveera — COMMENTED** [review]
Thanks for the PR, please share the example where this Skilljar LMS has been implemented

**Comment by kyletaylored** [comment]
https://learning.pantheon.io

**Comment by dhavalveera** [comment]
> https://learning.pantheon.io

when requesting a new technology, 4 - 5 examples are required

**Comment by kyletaylored** [comment]
- https://learn.procore.com
- https://learning.pantheon.io
- https://academy.asana.com
- https://learn.checkr.com
- https://training.zenefits.com

More customers listed here: https://www.skilljar.com/customers

**Review by nurbek91 — APPROVED** [review]

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
