### PR TITLE
Add AntiBot.Cloud / security #7285

### PR DESCRIPTION
**Pull request by nurbek91**
### website:
https://antibot.cloud/#pricing
### examples:
http://biofile.ru/
https://usamodelkina.ru/
https://sbankami.ru/

### CODE REVIEW

**Review by dhavalveera — CHANGES_REQUESTED** [review]
icon for `AntiBot.Cloud` is missing

**Comment by nurbek91** [comment]
> icon for `AntiBot.Cloud` is missing

Thanks do you have an icon?

**Comment by dhavalveera** [comment]
> > icon for `AntiBot.Cloud` is missing
> 
> Thanks do you have an icon?

actually, the AntiBot Cloud website is blocking me to access it due to which I don't have any access to get the logo, and that was the reason I didn't make a PR based on the Issue.

**Comment by John4266** [comment]
Their website is using the following icon: [favicon.ico](https://antibot.cloud/favicon.ico)
Hope it helps

**Comment by nurbek91** [comment]
> Their website favicon is the following: favicon.ico while their website page itself is using the Font Awesome `fa-shield-virus` icon https://fontawesome.com/icons/shield-virus Hope it helps


Can't download icon. Do you have the ability to hack things like that? : )

**Pull request merged**
