### PR TITLE
Add Solidstart Detection

### PR DESCRIPTION
**Pull request by ysm-dev**
base branch is `solidjs` (#7279)

https://start.solidjs.com/

ex)
- https://start.solidjs.com/
- https://codeimage.dev/
- https://auth-solid.vercel.app/
- https://ajcwebdev-solid.vercel.app/

### CODE REVIEW

**Comment by nurbek91** [comment]
Hey @ysm-dev 
Received such a request where he claims that he does not use SolidStart
How sure are you that this trace is correct?
`My website uses Astro and Soldjs which is correctly identified. But I have not used Solid Start https://guppybyte.com/ `

**Comment by nurbek91** [comment]
GPT say
Solidjs and SolidStart are two different things, but SolidStart is built on top of Solidjs.

Solidjs is a lightweight JavaScript library for building user interfaces. It follows a reactive programming model and uses a virtual DOM to efficiently update the UI. Solidjs provides a set of tools and APIs for creating and managing components, handling state and events, and rendering UI elements.

SolidStart, on the other hand, is a boilerplate for building web applications with Solidjs. It includes a set of preconfigured tools and plugins for setting up a development environment, handling routing, styling, and other common tasks. SolidStart provides a structure and some common patterns for building Solidjs applications, which can save time and effort when starting a new project.

So, in summary, Solidjs is the core library for building user interfaces, while SolidStart is a preconfigured setup for building web applications with Solidjs.

**Comment by ysm-dev** [comment]
> Hey @ysm-dev Received such a request where he claims that he does not use SolidStart How sure are you that this trace is correct? `My website uses Astro and Soldjs which is correctly identified. But I have not used Solid Start https://guppybyte.com/ `

hmm... that's weird.

I'm sure `_$HY` js is from `solid-start`, not `solidjs`

Seach `_$HY` in `solid-start`: https://github.com/search?q=repo%3Asolidjs%2Fsolid-start%20_%24HY&type=code

Search `_$HY` in `solid`: https://github.com/search?q=repo%3Asolidjs%2Fsolid%20_%24HY&type=code

**Comment by nurbek91** [comment]
Ok, I'll leave it up to youк know-how.

**Comment by nurbek91** [comment]
@ysm-dev Hey mate.
By this trail, can we tell that the technology uses SolidJS?
https://publicwww.com/websites/%22clr-i-solid+clr-i-solid-path-2%22/

**Comment by ceopeo** [comment]
Hey mate , https://robertonazareth.dev/ the developer of this site also claims that he does not use SolidStart

**Comment by ysm-dev** [comment]
@ceopeo Fix: #7818

**Pull request merged**
