### PR TITLE
More updates to categorisation

### PR DESCRIPTION
**Pull request by rockeynebhwani**
https://github.com/wappalyzer/wappalyzer/issues/5912

### CODE REVIEW

**Comment by nurbek91** [comment]
Hey @rockeynebhwani ,thanks!!!
How do you look if  replace for 5  HulkApps apps 
`"implies": "Shopify",`
to 
`"requires": "Shopify",`

**Comment by rockeynebhwani** [comment]
@nurbek91  - There is a growing trend of sites taking headless approach which means that it's not always possible to detect 'Shopify' but it's still possible to detect these apps.. and in that case, if we use 'implies', it helps with detection of 'Shopify' platform. Please also see - https://github.com/wappalyzer/wappalyzer/issues/6061

**Comment by nurbek91** [comment]
Hey @rockeynebhwani  Thank you, I didn't consider this question from this side.
I previously added the requires attribute for all Shopify applications
Thought it would help optimize performance.

Hey @AliasIO  What can you advise?
Change for all Shopify apps requires to implies?

**Comment by AliasIO** [comment]
Yes, it's a good point. Let's use `implies` for Shopify.

**Pull request merged**
