### PR TITLE
Add Endurance Page Cache plugin

### PR DESCRIPTION
**Pull request by kyletaylored**
The Endurance Page Cache plugin is a default WordPress plugin installed by shared hosts Bluehost and Hostgator.

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks! Could you add a square icon file?

**Comment by kyletaylored** [comment]
Yep, just updated it.

**Comment by AliasIO** [comment]
Thanks!

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
