### PR TITLE
Update Contentsquare logo and case

### PR DESCRIPTION
**Pull request by fviolette**
Hello — I work at Contentsquare.
Post a recent rebranding, this is our new logo.
The company name is Contentsquare, with just the C in capitals.

### CODE REVIEW

**Review by nurbek91 — CHANGES_REQUESTED** [review]
Hey mate, thanks for PR!!
Recommended file format is svg if available 32x32
[Contentsquare.svg.zip](https://github.com/wappalyzer/wappalyzer/files/8883555/Contentsquare.svg.zip)

**Comment by fviolette** [comment]
Updated.

**Comment by AliasIO** [comment]
It will be there when we publish a new version of the extension, this may take a few weeks.

**Comment by fviolette** [comment]
Thanks for the clarification

**Pull request merged**
