### PR TITLE
Detect if Polylang Pro or Polylang is used

### PR DESCRIPTION
**Pull request by sebastienserre**
Polylang have 2 version, a free on WP.org and a premium.This PR is detecting the difference.

### CODE REVIEW

**Comment by AliasIO** [comment]
Can we combine these and use 'Pro' as the version?

**Comment by sebastienserre** [comment]
Hello @AliasIO 
Unfortunately, there's nothing on front which announce the version number.

**Comment by AliasIO** [comment]
I mean we can have one entry for Polylang and detect 'Pro' as the version. This should work:

```
"headers": {
  "x-redirected-by": "Polylang(?: (Pro))?\\;version:\\1"
}
```

The `dom` pattern can be shortened to this:

```
"dom": "#pll_switcher"
```

**Comment by sebastienserre** [comment]
Thank you @AliasIO, I've modified the PR.

**Comment by AliasIO** [comment]
Thanks!

**Comment by sebastienserre** [comment]
Hello,
Is this closed PR has been integrated in apps? It seems not on y Chromium browser.
I also see an error on a GH action

**Comment by AliasIO** [comment]
Yes, this has been included everywhere. What error are you seeing?

**Comment by sebastienserre** [comment]
Hi,

As you can see the `x-redirect-by:` is set to `Polylang Pro` on this screenshot so Wappalyzer should display the Pro version.
Capture d’écran du 2022-11-18 08-55-29

**Pull request merged**
