### PR TITLE
Add Deno Deploy detection

### PR DESCRIPTION
**Pull request by ysm0622**
see #6413 first

website:
- https://deno.com/deploy

examples: 
- https://deno.land
- https://deno.com
- https://shield.deno.dev
- https://fresh.deno.dev
- https://lume.land

### CODE REVIEW

**Comment by AliasIO** [comment]
Thanks! Do you mind changing the PNG icon to SVG?

https://en.wikipedia.org/wiki/Deno_%28software%29#/media/File:Deno_2021.svg

I'm assuming Deno Deploy and Fresh should both imply Deno. Do you want to add Deno as a separate technology and add `"implies": "Deno"` to Deno Deploy and Fresh?

**Comment by ysm0622** [comment]
> Thanks! Do you mind changing the PNG icon to SVG?
Sure! [e29a46b](https://github.com/wappalyzer/wappalyzer/pull/6373/commits/e29a46b6be46a4d1e50c3be59c912e255b1885de)

> I'm assuming Deno Deploy and Fresh should both imply Deno. Do you want to add Deno as a separate technology and add "implies": "Deno" to Deno Deploy and Fresh?

Right, but currently, I think there is no way to detect Deno in the browser because of it's server-side runtime.
Still do you want me to add Deno without Json implementation for detection?
If yes, I will send another deno PR.

**Comment by AliasIO** [comment]
Yes, thanks! Some technologies can only indirectly detected and that's fine.

**Comment by ysm0622** [comment]
@AliasIO btw, plz check: https://github.com/wappalyzer/wappalyzer/pull/6358#issuecomment-1160885303

**Comment by ysm0622** [comment]
Deno #6413
I will update this PR after #6413 merged

**Comment by AliasIO** [comment]
Thanks!

**Pull request merged**
