### PR TITLE
Add Umso / page builder , fix Tailwind 

### PR DESCRIPTION
**Pull request by nurbek91**
### website
https://www.umso.com/pricing
### examples
https://audo.ai/
https://www.mixbloom.com/
https://sento.io/
###  `"scripts": "isPriorBlockingEnabled\\;confidence:75",`
https://coconseils.fr/
https://www.xpelise.fr/
https://www.recoup.com/

### CODE REVIEW

**Comment by Kikobeats** [comment]
I think this should to close #6099

Can you take a look, @AliasIO? 🙏

**Comment by AliasIO** [comment]
That was my bad, thanks @Kikobeats!

**Comment by Kikobeats** [comment]
no problem 🙂 appreciated if you can just release a new patch version at npm

**Comment by AliasIO** [comment]
Done!

**Comment by Kikobeats** [comment]
not sure, npm is still reporting latest version has the bug inside

> 6.10.22 • Public • Published 4 days ago

**Comment by AliasIO** [comment]
Pushed 6.10.23. 🤔

**Pull request merged**
