### PR TITLE
Straton Weather

### PR DESCRIPTION
**Pull request by StratonPro**
Hello, 

straton weather agency

https://straton.pro

# Technology request

### CODE REVIEW

**Comment by StratonPro** [comment]
Technology request

**Comment by StratonPro** [comment]
> 

Hello,

https://app.straton.pro
http://www.xalazi.gr/
http://www.simeteo.gr/
https://meteo-greece.gr/
https://freemeteo.gr/
https://www.forecastweather.gr/
https://www.meteogreece.net/

Thank You!

**Comment by nurbek91** [comment]
> > 
> 
> Hello,
> 
> https://app.straton.pro http://www.xalazi.gr/ http://www.simeteo.gr/ https://meteo-greece.gr/ https://freemeteo.gr/ https://www.forecastweather.gr/ https://www.meteogreece.net/
> 
> Thank You!
Sorry mate but I don't see the traces you provided in the examples

**Comment by StratonPro** [comment]
Hello,

See ours first, which has the most visits https://app.straton.pro
Your application normally runs on our own platform

others Programmers to do the installation correctly, other site :
http://www.xalazi.gr/ http://www.simeteo.gr/ https://meteo-greece.gr/ https://freemeteo.gr/ https://www.forecastweather.gr/ https://www.meteogreece.net/

**Comment by nurbek91** [comment]
> Hello,
> 
> See ours first, which has the most visits https://app.straton.pro Your application normally runs on our own platform
> 
> others Programmers to do the installation correctly, other site : http://www.xalazi.gr/ http://www.simeteo.gr/ https://meteo-greece.gr/ https://freemeteo.gr/ https://www.forecastweather.gr/ https://www.meteogreece.net/

Sorry mate, but I do not see that in other examples it is possible to define technology as a widget.

**Pull request closed without merging**
